config:
    # resolution
    resolution: [32, 32]
    # model name
    model_name: "safe_resnet18_cifar"
    # dataset name
    dataset_name: "cifar10"
    # train dataset
    train_dataset_path: "/datadrive/datasets/cifar10"
    # val dataset
    val_dataset_path: "/datadrive/datasets/cifar10"
    # train batch size per gpu
    train_batch_size: 128
    # number of epochs
    train_num_epochs: 30
    # restore from wandb or local
    train_restore_storage: ""
    # path to checkpoint from which to be restored
    train_restore_file: ""
    # learning rate
    learning_rate: 0.01
    # validation batch size
    val_batch_size: 128
    # log freq
    train_log_freq: 100
    # train save freq in epochs
    train_save_freq: 1
